name: journee
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  camera: ^0.11.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  cloud_firestore: ^6.1.1
  uuid: ^4.5.2
  path: ^1.9.1
  path_provider: ^2.1.5
  geolocator: ^14.0.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.1
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  geocoding: ^2.0.5
  table_calendar: ^3.2.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_app.png
    - assets/images/cloud.png
    - assets/images/cloud_left.png
    - assets/images/cloud_right.png
    - assets/images/icon_book.png
    - assets/images/icon_book_f.png
    - assets/images/icon_calendar.png
    - assets/images/icon_calendar_f.png
    - assets/images/icon_setting.png
    - assets/images/icon_setting_f.png
    - assets/images/icon_star.png
    - assets/images/mountain.png
    - assets/images/trees.png
    - assets/images/launch_icon.png
    - assets/images/icon_camera.png
    - assets/icons/back.png
    - assets/icons/flash.png
    - assets/icons/switch_camera.png
    - assets/icons/camera.png



  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch_icon.png"

flutter_native_splash:
  android: true
  ios: true
  image: assets/images/launch_icon.png
  color: "#ffffff"